<a href="https://colab.research.google.com/github/tungduong03/Deep-Learning/blob/main/Data_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

**Data capec multilabel dataset**

Data đang ở dạng multilabel

In [5]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Code_Injection_Dataset
df_capec = pd.read_csv('data_capec_multilabel.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Code_Injection_Dataset

<ipython-input-5-b208298faa3c>:4: DtypeWarning: Columns (9,11,12,13,14,15,16,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df_capec = pd.read_csv('data_capec_multilabel.csv')

In [6]:
df_capec.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling
0,17/Jul/2020:12:23:34 +0100,172.26.0.1,55894.0,172.26.0.4,80.0,GET,/,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,25174.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20862.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,317.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,17/Jul/2020:12:23:51 +0100,172.26.0.1,55902.0,172.26.0.4,80.0,GET,/,HTTP/1.1,Mozilla/5.0 (Linux; Android 4.2.2; SM-T110 Bui...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,25174.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20863.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
## Delete blank text in http request - Xóa các "request_http_request" = '/'
df_capec = df_capec[df_capec['request_http_request'] != '/']

In [8]:
df_capec.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20862.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,317.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20863.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
5,17/Jul/2020:12:24:07 +0100,172.26.0.1,55910.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21062.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
6,17/Jul/2020:12:24:15 +0100,172.26.0.1,55911.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21061.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

**Convert from multilabel to multiclass**

Chuyển từ multilabel về 1 label

In [9]:
df_capec.shape

(608806, 38)

In [11]:
def count_duplicate(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13):
    return a0+a1+a2+a3+a4+a5+a6+a7+a8+a9+a10+a11+a12+a13

# tạo 1 cột count tính tổng các label được gán
df_capec['count'] = df_capec.apply(lambda x: count_duplicate(x['000 - Normal'],
                                                             x['272 - Protocol Manipulation'],
                                                             x['242 - Code Injection'],
                                                             x['88 - OS Command Injection'],
                                                             x['126 - Path Traversal'],
                                                             x['66 - SQL Injection'],
                                                             x['16 - Dictionary-based Password Attack'],
                                                             x['310 - Scanning for Vulnerable Software'],
                                                             x['153 - Input Data Manipulation'],
                                                             x['248 - Command Injection'],
                                                             x['274 - HTTP Verb Tampering'],
                                                             x['194 - Fake the Source of Data'],
                                                             x['34 - HTTP Response Splitting'],
                                                             x['33 - HTTP Request Smuggling']), axis = 1)

In [13]:
# Data with only multiclass - lấy ra data label có count = 1
df_multiclass = df_capec[df_capec['count']==1]

In [14]:
df_multiclass.shape

(599755, 39)

In [15]:
df_multiclass.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20862.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,317.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20863.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5,17/Jul/2020:12:24:07 +0100,172.26.0.1,55910.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21062.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6,17/Jul/2020:12:24:15 +0100,172.26.0.1,55911.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21061.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [17]:
# Data with multilabel - lấy data có count > 1
df_multilabel = df_capec[df_capec['count']>1]

In [18]:
df_multilabel.shape

(9051, 39)

In [19]:
df_multilabel.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
2940,17/Jul/2020:19:01:39 +0200,172.26.0.1,45500.0,172.26.0.4,80.0,POST,/vendor/phpunit/phpunit/src/Util/PHP/eval-stdi...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,172.26.0.1:80,NaN,NaN,application/x-www-form-urlencoded,NaN,NaN,gzip,NaN,close,"<?=md5(""phpunit"")?>",HTTP/1.1,404.0,Not Found,275.0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,2
2961,17/Jul/2020:19:11:23 +0200,172.26.0.1,47482.0,172.26.0.4,80.0,POST,/cgi-bin/ViewLog.asp,HTTP/1.1,B4ckdoor-owned-you,NaN,127.0.0.1,NaN,NaN,application/x-www-form-urlencoded,*/*,NaN,"gzip, deflate",NaN,keep-alive,remote_submit_Flag=1&remote_syslog_Flag=1&Rem...,HTTP/1.1,404.0,Not Found,271.0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,2
2969,17/Jul/2020:19:25:15 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/.svn/wc.db,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,2
2974,17/Jul/2020:19:25:16 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/blog/.svn/wc.db,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,2
2977,17/Jul/2020:19:25:16 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/blog/index.php/my-account/.svn/wc.db,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,58226.0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,2

**66 - SQL Injection**

In [20]:
# Assign for test only
df_capec = df_multiclass
df_sqli = df_capec[df_capec['66 - SQL Injection'] == 1].loc[:, ['request_http_method',
                                                                'request_http_request',
                                                                'request_body',
                                                                '66 - SQL Injection']].reset_index(drop=True)

In [21]:
df_sqli.head()

,request_http_method,request_http_request,request_body,66 - SQL Injection
0,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,NaN,1
1,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,NaN,1
2,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,NaN,1
3,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,NaN,1
4,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,NaN,1

In [22]:
df_sqli = df_capec[df_capec['66 - SQL Injection'] == 1]

In [23]:
df_sqli.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
3121,17/Jul/2020:19:25:48 +0200,172.26.0.1,59867.0,172.26.0.4,80.0,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,200.0,OK,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
4255,17/Jul/2020:19:33:20 +0200,172.26.0.1,59968.0,172.26.0.4,80.0,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,200.0,OK,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
7159,17/Jul/2020:20:01:20 +0200,172.26.0.1,63063.0,172.26.0.4,80.0,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,https://test-site.com/blog/wp-login.php?logged...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,NaN,"text/css,*/*;q=0.1","en-US,en;q=0.5",NaN,1.0,keep-alive,NaN,HTTP/1.1,200.0,OK,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
7758,17/Jul/2020:21:27:43 +0200,172.26.0.1,64594.0,172.26.0.4,80.0,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php?action=...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,200.0,OK,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
8188,17/Jul/2020:21:29:12 +0200,172.26.0.1,64609.0,172.26.0.4,80.0,GET,/blog/wp-admin/load-styles.php?c=0&dir=ltr&loa...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,200.0,OK,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1

In [24]:
df_sqli.shape

(248093, 39)

**194 - Fake the Source of Data**

In [25]:
df_fake = df_capec[df_capec['194 - Fake the Source of Data'] == 1].loc[:, ['request_http_method',
                                                                           'request_http_request',
                                                                           'request_body',
                                                                           '194 - Fake the Source of Data']].reset_index(drop=True)

In [26]:
df_fake.head()

,request_http_method,request_http_request,request_body,194 - Fake the Source of Data
0,GET,/http%3A%2F%2Fwww.google.com%2F,NaN,1
1,GET,/http%3A%2F%2Fwww.google.com%2F/index.php,NaN,1
2,GET,/http%3A%2F%2Fwww.google.com%3A80%2F,NaN,1
3,GET,/http%3A%2F%2Fwww.google.com%3A80%2F/index.php,NaN,1
4,GET,/http%3A%2F%2Fwww.google.com,NaN,1

In [27]:
df_fake = df_capec[df_capec['194 - Fake the Source of Data'] == 1]

In [28]:
df_fake.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
44501,17/Jul/2020:22:24:07 +0200,172.26.0.1,65225.0,172.26.0.4,80.0,GET,/http%3A%2F%2Fwww.google.com%2F,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,NaN,keep-alive,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
44502,17/Jul/2020:22:24:07 +0200,172.26.0.1,65227.0,172.26.0.4,80.0,GET,/http%3A%2F%2Fwww.google.com%2F/index.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
44504,17/Jul/2020:22:24:07 +0200,172.26.0.1,65228.0,172.26.0.4,80.0,GET,/http%3A%2F%2Fwww.google.com%3A80%2F,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,NaN,keep-alive,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
44505,17/Jul/2020:22:24:07 +0200,172.26.0.1,65227.0,172.26.0.4,80.0,GET,/http%3A%2F%2Fwww.google.com%3A80%2F/index.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
44506,17/Jul/2020:22:24:07 +0200,172.26.0.1,65227.0,172.26.0.4,80.0,GET,/http%3A%2F%2Fwww.google.com,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,NaN,keep-alive,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1

In [29]:
df_fake.shape

(55982, 39)

**242 - Code Injection**

In [30]:
df_injection = df_path_traversal = df_capec[df_capec['242 - Code Injection'] == 1].loc[:, ['request_http_method',
                                                                                           'request_http_request',
                                                                                           'request_body',
                                                                                           '242 - Code Injection']].reset_index(drop=True)

In [31]:
df_injection = df_path_traversal = df_capec[df_capec['242 - Code Injection'] == 1]

In [32]:
df_injection.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
7491,17/Jul/2020:20:08:51 +0200,172.26.0.1,36158.0,172.26.0.4,80.0,GET,/index.php?s=/Index/\x5Cthink\x5Capp/invokefun...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"deflate, gzip",NaN,NaN,NaN,HTTP/1.1,200.0,OK,18839.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
110025,17/Jul/2020:23:36:11 +0200,172.26.0.1,50100.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,username=%22%3E%3Cscript%3Ealert%281%29%3B%3C%...,HTTP/1.1,200.0,OK,58064.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
110026,17/Jul/2020:23:36:12 +0200,172.26.0.1,50101.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,username=%22+onMouseOver%3D%22alert%281%29%3B&...,HTTP/1.1,200.0,OK,58051.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
110067,17/Jul/2020:23:36:19 +0200,172.26.0.1,50103.0,172.26.0.4,80.0,GET,/blog/index.php/my-account/edit-profile/post.p...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,200.0,OK,57915.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
110068,17/Jul/2020:23:36:19 +0200,172.26.0.1,50101.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-profile/post.p...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,username=wakefulViper3&password=GJLU7ABS&user-...,HTTP/1.1,200.0,OK,58150.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1

In [33]:
df_injection.shape

(13792, 39)

**34 - HTTP Response Splitting**

In [34]:
df_response = df_capec[df_capec['34 - HTTP Response Splitting'] == 1].loc[:, ['request_http_method',
                                                                              'request_http_request',
                                                                              'request_body',
                                                                              '34 - HTTP Response Splitting']].reset_index(drop=True)

In [35]:
df_response = df_capec[df_capec['34 - HTTP Response Splitting'] == 1]

In [36]:
df_response.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
242072,18/Jul/2020:03:22:32 +0200,172.26.0.1,62915.0,172.26.0.4,80.0,GET,/blog%0Acat+%2Fetc%2Fpasswd%0A,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,NaN,keep-alive,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
242073,18/Jul/2020:03:22:32 +0200,172.26.0.1,62914.0,172.26.0.4,80.0,GET,/blog%0Acat+%2Fetc%2Fpasswd%0A/index.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
242096,18/Jul/2020:03:22:34 +0200,172.26.0.1,62915.0,172.26.0.4,80.0,GET,/blog%0Asleep+15%0A,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,NaN,keep-alive,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
242097,18/Jul/2020:03:22:34 +0200,172.26.0.1,62914.0,172.26.0.4,80.0,GET,/blog%0Asleep+15%0A/index.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
242121,18/Jul/2020:03:22:37 +0200,172.26.0.1,62915.0,172.26.0.4,80.0,GET,/blog%0Acat+%2Fetc%2Fpasswd%0A/index.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,NaN,keep-alive,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1

In [37]:
df_response.shape

(19134, 39)

**000 - Normal**

In [38]:
df_normal = df_capec[df_capec['000 - Normal'] == 1].loc[:, ['request_http_method',
                                                            'request_http_request',
                                                            'request_body',
                                                            '000 - Normal']].reset_index(drop=True)

In [39]:
df_normal = df_capec[df_capec['000 - Normal'] == 1]

In [40]:
df_normal.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20862.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,317.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20863.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5,17/Jul/2020:12:24:07 +0100,172.26.0.1,55910.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21062.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6,17/Jul/2020:12:24:15 +0100,172.26.0.1,55911.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21061.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [41]:
df_normal.shape

(226509, 39)

**272 - Protocol Manipulation**

In [42]:
df_protocol = df_capec[df_capec['272 - Protocol Manipulation'] == 1].loc[:, ['request_http_method',
                                                                             'request_http_request',
                                                                             'request_body',
                                                                             '000 - Normal']].reset_index(drop=True)

In [43]:
df_protocol = df_capec[df_capec['272 - Protocol Manipulation'] == 1]

In [44]:
df_protocol.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
3461,17/Jul/2020:19:30:37 +0200,172.26.0.1,59927.0,172.26.0.4,80.0,GET,/blog/index.php/my-account/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,172.26.0.1,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","en-US,en;q=0.5",NaN,1.0,keep-alive,NaN,HTTP/1.1,200.0,OK,57822.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
7138,17/Jul/2020:19:58:39 +0200,172.26.0.1,63015.0,172.26.0.4,80.0,GET,/blog/wp-content/uploads/2020/04/c874f043-4188...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,172.26.0.1,NaN,NaN,NaN,"image/webp,*/*","en-US,en;q=0.5",NaN,1.0,keep-alive,NaN,HTTP/1.1,200.0,OK,78796.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
7139,17/Jul/2020:19:58:39 +0200,172.26.0.1,63016.0,172.26.0.4,80.0,GET,/blog/wp-content/uploads/2020/04/5d0beb80-cdb9...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,NaN,172.26.0.1,NaN,NaN,NaN,"image/webp,*/*","en-US,en;q=0.5",NaN,1.0,keep-alive,NaN,HTTP/1.1,200.0,OK,236440.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
7508,17/Jul/2020:20:09:38 +0200,172.26.0.1,64214.0,172.26.0.4,80.0,GET,/blog/wp-content/uploads/2020/04/8427d570-74b5...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,http://test-site.com/,172.26.0.1,NaN,NaN,NaN,"image/webp,*/*","en-US,en;q=0.5","gzip, deflate",1.0,keep-alive,NaN,HTTP/1.1,200.0,OK,2255.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
7509,17/Jul/2020:20:09:38 +0200,172.26.0.1,64213.0,172.26.0.4,80.0,GET,/blog/wp-content/uploads/2020/04/cda5c6a3-e3d9...,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko...,http://test-site.com/,172.26.0.1,NaN,NaN,NaN,"image/webp,*/*","en-US,en;q=0.5","gzip, deflate",1.0,keep-alive,NaN,HTTP/1.1,200.0,OK,1461.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1

In [45]:
df_protocol.shape

(6924, 39)

**88 - OS Command Injection**

In [46]:
df_os = df_capec[df_capec['88 - OS Command Injection'] == 1].loc[:, ['request_http_method',
                                                                     'request_http_request',
                                                                     'request_body',
                                                                     '000 - Normal']].reset_index(drop=True)

In [47]:
df_os = df_capec[df_capec['88 - OS Command Injection'] == 1]

In [48]:
df_os.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
7494,17/Jul/2020:20:08:52 +0200,172.26.0.1,36158.0,172.26.0.4,80.0,GET,/index.php?s=/module/action/param1/${@die(sha1...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"deflate, gzip",NaN,NaN,NaN,HTTP/1.1,200.0,OK,18869.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
257238,18/Jul/2020:04:08:39 +0200,172.26.0.1,63219.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,comment_author_url_1aefbe2f76edd740f8e362f39da...,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,password_current=aH2q*Rj%26sleep+15%26&passwor...,HTTP/1.1,200.0,OK,57821.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
257240,18/Jul/2020:04:08:39 +0200,172.26.0.1,63219.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,comment_author_url_1aefbe2f76edd740f8e362f39da...,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,password_current=H#bO2%3Bsleep+15%3B&password_...,HTTP/1.1,200.0,OK,57821.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
257242,18/Jul/2020:04:08:40 +0200,172.26.0.1,63219.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,comment_author_url_1aefbe2f76edd740f8e362f39da...,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,password_current=muRWD%22%26sleep+15%26%22&pas...,HTTP/1.1,200.0,OK,57821.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
257244,18/Jul/2020:04:08:40 +0200,172.26.0.1,63219.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,comment_author_url_1aefbe2f76edd740f8e362f39da...,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,password_current=3X*Bam%22%3Bsleep+15%3B%22&pa...,HTTP/1.1,200.0,OK,57821.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1

In [49]:
df_os.shape

(3074, 39)

**126 - Path Traversal**

In [50]:
df_path_traveral = df_capec[df_capec['126 - Path Traversal'] == 1].loc[:, ['request_http_method',
                                                                           'request_http_request',
                                                                           'request_body',
                                                                           '000 - Normal']].reset_index(drop=True)

In [51]:
df_path_traveral = df_capec[df_capec['126 - Path Traversal'] == 1]

In [52]:
df_path_traveral.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
2968,17/Jul/2020:19:25:15 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/.svn/entries,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2970,17/Jul/2020:19:25:15 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/.git/index,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2973,17/Jul/2020:19:25:16 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/blog/.svn/entries,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2975,17/Jul/2020:19:25:16 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/blog/.git/index,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,276.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2976,17/Jul/2020:19:25:16 +0200,172.26.0.1,59862.0,172.26.0.4,80.0,GET,/blog/index.php/my-account/.svn/entries,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,wordpress_logged_in_1aefbe2f76edd740f8e362f39d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,404.0,Not Found,58226.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1

In [53]:
df_path_traveral.shape

(17595, 39)

**16 - Dictionary-based Password Attack**

In [54]:
df_dict = df_capec[df_capec['16 - Dictionary-based Password Attack'] == 1]

In [55]:
df_dict.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
3122,17/Jul/2020:19:25:48 +0200,172.26.0.1,59863.0,172.26.0.4,80.0,POST,/blog/wp-login.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,log=rafael&pwd=975cU&rememberme=forever&wp-sub...,HTTP/1.1,200.0,OK,4215.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
3351,17/Jul/2020:19:26:25 +0200,172.26.0.1,59870.0,172.26.0.4,80.0,POST,/blog/wp-login.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php?loggedo...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,log=thrilledCrackers6&pwd=hOKxTw_2&rememberme=...,HTTP/1.1,200.0,OK,4209.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
4565,17/Jul/2020:19:33:33 +0200,172.26.0.1,59973.0,172.26.0.4,80.0,POST,/blog/wp-login.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,log=innocentOwl1&pwd=41IPdtwh&rememberme=forev...,HTTP/1.1,200.0,OK,4209.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
4730,17/Jul/2020:19:33:50 +0200,172.26.0.1,59975.0,172.26.0.4,80.0,POST,/blog/wp-login.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php?reauth=...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,log=panickyEagle4&pwd=cXTkX&rememberme=forever...,HTTP/1.1,200.0,OK,4218.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
4731,17/Jul/2020:19:33:50 +0200,172.26.0.1,59975.0,172.26.0.4,80.0,POST,/blog/wp-login.php,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/wp-login.php?reauth=...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,application/x-www-form-urlencoded,NaN,NaN,NaN,NaN,NaN,log=trustingOatmeal8&pwd=qqIzM7vt&rememberme=f...,HTTP/1.1,200.0,OK,4220.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1

In [56]:
df_dict.shape

(836, 39)

**310 - Scanning for Vulnerable Software**

In [57]:
df_scanning = df_capec[df_capec['310 - Scanning for Vulnerable Software'] == 1]

In [58]:
df_scanning.tail()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
7473,17/Jul/2020:20:06:19 +0200,172.26.0.1,64144.0,172.26.0.4,80.0,GET,/mt-static/mt-config.cgi.save,HTTP/1.1,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,249.network5-175-62-15.static.network5.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,close,NaN,HTTP/1.1,404.0,Not Found,301.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
7480,17/Jul/2020:20:06:21 +0200,172.26.0.1,64151.0,172.26.0.4,80.0,GET,/%23settings.php%23,HTTP/1.1,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,249.network5-175-62-15.static.network5.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,close,NaN,HTTP/1.1,404.0,Not Found,301.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
7481,17/Jul/2020:20:06:21 +0200,172.26.0.1,64152.0,172.26.0.4,80.0,GET,/settings%20copy.php,HTTP/1.1,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,249.network5-175-62-15.static.network5.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,close,NaN,HTTP/1.1,404.0,Not Found,301.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
7482,17/Jul/2020:20:06:21 +0200,172.26.0.1,64153.0,172.26.0.4,80.0,GET,/Copy%20of%20settings.php,HTTP/1.1,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,249.network5-175-62-15.static.network5.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,close,NaN,HTTP/1.1,404.0,Not Found,301.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
7483,17/Jul/2020:20:06:21 +0200,172.26.0.1,64154.0,172.26.0.4,80.0,GET,/settings.php.save,HTTP/1.1,Mozilla/5.0 (compatible; Nmap Scripting Engine...,NaN,249.network5-175-62-15.static.network5.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,close,NaN,HTTP/1.1,404.0,Not Found,301.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1

In [59]:
df_scanning.shape

(2382, 39)

**153 - Input Data Manipulation**

In [60]:
df_input = df_capec[df_capec['153 - Input Data Manipulation'] == 1]

In [61]:
df_input.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
19406,17/Jul/2020:21:48:16 +0200,172.26.0.1,64765.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,/etc/passwd,NaN,NaN,NaN,NaN,NaN,password_current=76U8B7&password_1=76U8B7&pass...,HTTP/1.1,200.0,OK,57821.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
19411,17/Jul/2020:21:48:17 +0200,172.26.0.1,64763.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,etc/passwd,NaN,NaN,NaN,NaN,NaN,password_current=ltHgBOO&password_1=ltHgBOO&pa...,HTTP/1.1,200.0,OK,57821.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
19413,17/Jul/2020:21:48:17 +0200,172.26.0.1,64765.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,c:/,NaN,NaN,NaN,NaN,NaN,password_current=5uSt9Xd&password_1=5uSt9Xd&pa...,HTTP/1.1,200.0,OK,57821.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
19415,17/Jul/2020:21:48:17 +0200,172.26.0.1,64765.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,/,NaN,NaN,NaN,NaN,NaN,password_current=J875f&password_1=J875f&passwo...,HTTP/1.1,200.0,OK,57821.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
19416,17/Jul/2020:21:48:17 +0200,172.26.0.1,64763.0,172.26.0.4,80.0,POST,/blog/index.php/my-account/edit-password/,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,http://test-site.com/blog/index.php/my-account...,test-site.com,NaN,wordpress_test_cookie=WP+Cookie+check,c:\,NaN,NaN,NaN,NaN,NaN,password_current=C&rclFh&password_1=C&rclFh&pa...,HTTP/1.1,200.0,OK,57821.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1

In [62]:
df_input.shape

(1387, 39)

**274 - HTTP Verb Tampering**

In [63]:
df_http_verb = df_capec[df_capec['274 - HTTP Verb Tampering'] == 1]

In [64]:
df_http_verb.tail()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count
543488,19/Jul/2020:11:49:29 +0200,172.26.0.1,56039.0,172.26.0.4,80.0,MKCOL,/sitemap.xml,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,405.0,Method Not Allowed,302.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
543489,19/Jul/2020:11:49:29 +0200,172.26.0.1,56039.0,172.26.0.4,80.0,MOVE,/sitemap.xml,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,405.0,Method Not Allowed,301.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
543490,19/Jul/2020:11:49:29 +0200,172.26.0.1,56039.0,172.26.0.4,80.0,PROPFIND,/sitemap.xml,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,405.0,Method Not Allowed,305.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
543491,19/Jul/2020:11:49:29 +0200,172.26.0.1,56039.0,172.26.0.4,80.0,PROPPATCH,/sitemap.xml,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,405.0,Method Not Allowed,306.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
543492,19/Jul/2020:11:49:29 +0200,172.26.0.1,56039.0,172.26.0.4,80.0,UNLOCK,/sitemap.xml,HTTP/1.1,Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko...,NaN,test-site.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTTP/1.1,405.0,Method Not Allowed,303.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1

In [65]:
df_http_verb.shape

(4047, 39)

**Prepare and format data**

In [67]:
# Concat http_method with http_request and http_content
def create_text(method, request, body):
    if method == 'GET':
        return str(method) + ' ' + str(request)
    return str(method) + ' ' + str(request) + ' ' + str(body)

# ghép các cột lại thành 1 cột `text`
df_capec['text'] = df_capec.apply(lambda x: create_text(x['request_http_method'],
                                                        x['request_http_request'],
                                                        x['request_body']), axis = 1)

In [68]:
df_capec.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count,text
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20862.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/voluptatum-repr...
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,317.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/xmlrpc.php?rsd
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20863.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/nihil-tenetur-e...
5,17/Jul/2020:12:24:07 +0100,172.26.0.1,55910.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21062.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/explicabo-qui-f...
6,17/Jul/2020:12:24:15 +0100,172.26.0.1,55911.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21061.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/explicabo-qui-f...

In [69]:
# Mapping values for classification - Gắn nhãn, khi nhãn ở cột nào sẽ gán cho trường `label` tên lỗ hổng đó
def count_duplicate(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13):
    if a0 == 1:
        return '000 - Normal'
    elif a1 == 1:
        return '272 - Protocol Manipulation'
    elif a2 == 1:
        return '242 - Code Injection'
    elif a3 == 1:
        return '88 - OS Command Injection'
    elif a4 == 1:
        return '126 - Path Traversal'
    elif a5 == 1:
        return '66 - SQL Injection'
    elif a6 == 1:
        return '16 - Dictionary-based Password Attack'
    elif a7 == 1:
        return '310 - Scanning for Vulnerable Software'
    elif a8 == 1:
        return '153 - Input Data Manipulation'
    elif a9 == 1:
        return '248 - Command Injection'
    elif a10 == 1:
        return '274 - HTTP Verb Tampering'
    elif a11 == 1:
        return '194 - Fake the Source of Data'
    elif a12 == 1:
        return '34 - HTTP Response Splitting'
    elif a13 == 1:
        return '33 - HTTP Request Smuggling'
    return 'Error'


df_capec['label'] = df_capec.apply(lambda x: count_duplicate(x['000 - Normal'],
                                                             x['272 - Protocol Manipulation'],
                                                             x['242 - Code Injection'],
                                                             x['88 - OS Command Injection'],
                                                             x['126 - Path Traversal'],
                                                             x['66 - SQL Injection'],
                                                             x['16 - Dictionary-based Password Attack'],
                                                             x['310 - Scanning for Vulnerable Software'],
                                                             x['153 - Input Data Manipulation'],
                                                             x['248 - Command Injection'],
                                                             x['274 - HTTP Verb Tampering'],
                                                             x['194 - Fake the Source of Data'],
                                                             x['34 - HTTP Response Splitting'],
                                                             x['33 - HTTP Request Smuggling']), axis = 1)

In [70]:
df_capec.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,request_host,request_origin,request_cookie,request_content_type,request_accept,request_accept_language,request_accept_encoding,request_do_not_track,request_connection,request_body,response_http_protocol,response_http_status_code,response_http_status_message,response_content_length,000 - Normal,272 - Protocol Manipulation,242 - Code Injection,88 - OS Command Injection,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling,count,text,label
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20862.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/voluptatum-repr...,000 - Normal
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,317.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/xmlrpc.php?rsd,000 - Normal
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,20863.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/nihil-tenetur-e...,000 - Normal
5,17/Jul/2020:12:24:07 +0100,172.26.0.1,55910.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21062.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/explicabo-qui-f...,000 - Normal
6,17/Jul/2020:12:24:15 +0100,172.26.0.1,55911.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/explicabo-qui-fuga-...,HTTP/1.1,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...,NaN,test-site.com,NaN,NaN,NaN,*/*,NaN,"gzip, deflate",NaN,keep-alive,NaN,HTTP/1.1,200.0,OK,21061.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,GET /blog/index.php/2020/04/04/explicabo-qui-f...,000 - Normal

In [71]:
df_training = df_capec[(df_capec['label'] != '33 - HTTP Request Smuggling')
                        & (df_capec['label'] != '248 - Command Injection')
                        & (df_capec['label'] != '16 - Dictionary-based Password Attack')
                        & (df_capec['label'] != '274 - HTTP Verb Tampering')
                        & (df_capec['label'] != '88 - OS Command Injection')]

In [72]:
df_capec.shape

(599755, 41)

In [73]:
df_training.shape

(591798, 41)

In [74]:
# List of label
df_training.label.unique()

array(['000 - Normal', '126 - Path Traversal', '66 - SQL Injection',
       '272 - Protocol Manipulation',
       '310 - Scanning for Vulnerable Software', '242 - Code Injection',
       '153 - Input Data Manipulation', '194 - Fake the Source of Data',
       '34 - HTTP Response Splitting'], dtype=object)

In [75]:
# lọc data chỉ lấy ra phần text và label
df_final = df_training.loc[:, ['text','label']].reset_index(drop=True)

In [76]:
df_final.head()

                                                text         label
0  GET /blog/index.php/2020/04/04/voluptatum-repr...  000 - Normal
1                           GET /blog/xmlrpc.php?rsd  000 - Normal
2  GET /blog/index.php/2020/04/04/nihil-tenetur-e...  000 - Normal
3  GET /blog/index.php/2020/04/04/explicabo-qui-f...  000 - Normal
4  GET /blog/index.php/2020/04/04/explicabo-qui-f...  000 - Normal

In [ ]:
# Save to csv
df_final.to_csv('dataset_capec.csv', encoding='utf-8', index=False)